services:
  - type: web
    name: streamlit-irctc
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
